# -*- coding: utf-8 -*-
"""khushi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LD-laBfDrUhu0l2sLvXE5pQVJwOgOEl0
"""

print('hello')